name: Deploy

on:
  push:
    branches: [ develop ]
  release:
    types: [ published ]

env:
  NODE_VERSION: '18'

jobs:
  # Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build Backend
        run: |
          echo "🔧 Building Backend..."
          cd backend
          npm ci
          npm run build
          echo "✅ Backend built successfully!"

      - name: Build Frontend
        run: |
          echo "🔧 Building Frontend..."
          cd frontend
          npm ci
          npm run build
          echo "✅ Frontend built successfully!"

      - name: Deploy to Staging
        run: |
          echo "🚀 Deploying to Staging Environment..."
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
          
          # Add your staging deployment logic here
          # Example: kubectl apply, docker-compose, etc.
          echo "✅ Staging deployment completed!"

      - name: Notify Staging Deployment
        run: |
          echo "📢 Staging deployment notification sent!"
          # Add your notification logic here
          # Example: Slack, email, etc.

  # Deploy to Production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build Backend
        run: |
          echo "🔧 Building Backend..."
          cd backend
          npm ci
          npm run build
          echo "✅ Backend built successfully!"

      - name: Build Frontend
        run: |
          echo "🔧 Building Frontend..."
          cd frontend
          npm ci
          npm run build
          echo "✅ Frontend built successfully!"

      - name: Deploy to Production
        run: |
          echo "🚀 Deploying to Production Environment..."
          echo "Release: ${{ github.event.release.tag_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Author: ${{ github.actor }}"
          
          # Add your production deployment logic here
          # Example: kubectl apply, docker-compose, etc.
          echo "✅ Production deployment completed!"

      - name: Notify Production Deployment
        run: |
          echo "📢 Production deployment notification sent!"
          # Add your notification logic here
          # Example: Slack, email, etc.

      - name: Run Post-Deployment Checks
        run: |
          echo "🔍 Running Post-Deployment Checks..."
          
          # Health check endpoints
          # curl -f https://your-domain.com/health || exit 1
          
          # Database connectivity
          # curl -f https://your-domain.com/api/health || exit 1
          
          echo "✅ Post-deployment checks passed!"

  # Rollback (if needed)
  rollback:
    name: Rollback
    runs-on: ubuntu-latest
    if: failure() && github.event_name == 'release'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rollback Production
        run: |
          echo "🔄 Rolling back production deployment..."
          echo "Release: ${{ github.event.release.tag_name }}"
          
          # Add your rollback logic here
          # Example: kubectl rollback, docker-compose down, etc.
          echo "✅ Rollback completed!"

      - name: Notify Rollback
        run: |
          echo "📢 Rollback notification sent!"
          # Add your notification logic here